language: php
sudo: trues
php:
  - 7.1
  - 7.2
  - 7.3

env:
  - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
  - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
  - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
  - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=~7.5

matrix:
  fast_finish: true

before_install:
  - composer require "laravel/framework:${ILLUMINATE_VERSION}" --no-update --prefer-dist
  - composer require "orchestra/testbench:${ILLUMINATE_VERSION/5\./3\.}" --no-update --prefer-dist
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install:
  ## back dependencies
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer install --prefer-source --no-interaction
  ## front dependencies
  - . $HOME/.nvm/nvm.sh
  - nvm install 11.6
  - nvm use 11.6
  - npm install

script:
  - vendor/bin/phpunit
  - npm run test
